import os
import re
import sqlite3
from contextlib import contextmanager
from pathlib import Path
from urllib.parse import parse_qs, urlsplit

import psycopg
from psycopg.rows import dict_row

IntegrityErrors = (sqlite3.IntegrityError, psycopg.IntegrityError)
DatabaseErrors = (sqlite3.DatabaseError, psycopg.Error)


class PostgresDatabase:
    def __init__(self, connection):
        self.connection = connection

    @staticmethod
    def query(sql, parameters):
        # アプリ内の固定SQLだけを変換する。入力値はドライバーに別途渡す。
        if isinstance(parameters, dict):
            return re.sub(r":([a-zA-Z_][a-zA-Z_0-9]*)", r"%(\1)s", sql)
        return sql.replace("?", "%s")

    def execute(self, sql, parameters=None):
        return self.connection.execute(self.query(sql, parameters), parameters)

    def executemany(self, sql, parameters):
        with self.connection.cursor() as cursor:
            cursor.executemany(self.query(sql, None), parameters)

    def executescript(self, sql):
        # 初期化用DDLは単純な文のみ。関数定義やユーザー入力は扱わない。
        for statement in sql.split(";"):
            if statement.strip():
                self.execute(statement)


def lock_auth(db):
    if isinstance(db, PostgresDatabase):
        # 複数のサーバーでもログイン試行回数の更新を直列化する。
        db.execute("SELECT pg_advisory_xact_lock(73120401)")
    else:
        db.execute("BEGIN IMMEDIATE")


@contextmanager
def database():
    url = os.getenv("DATABASE_URL", "").strip()
    if url:
        parsed = urlsplit(url)
        if parsed.scheme not in {"postgres", "postgresql"}:
            raise ValueError("DATABASE_URLにはPostgreSQLの接続URLを設定してください。")
        options = {} if "sslmode" in parse_qs(parsed.query) else {"sslmode": "require"}
        with psycopg.connect(url, row_factory=dict_row, connect_timeout=10, prepare_threshold=None, **options) as connection:
            connection.execute("SET LOCAL search_path TO ictsol")
            yield PostgresDatabase(connection)
        return
    if os.getenv("REQUIRE_DATABASE_URL") == "1":
        raise RuntimeError("公開環境ではDATABASE_URLの設定が必要です。")
    path = Path(os.getenv("DATABASE_PATH", str(Path(__file__).resolve().parents[1] / "data" / "app.sqlite3")))
    path.parent.mkdir(parents=True, exist_ok=True)
    connection = sqlite3.connect(path, timeout=10)
    connection.row_factory = sqlite3.Row
    try:
        with connection:
            yield connection
    finally:
        connection.close()


def initialize():
    with database() as db:
        postgres = isinstance(db, PostgresDatabase)
        if postgres:
            db.execute("SELECT pg_advisory_xact_lock(73120402)")
            db.execute("CREATE SCHEMA IF NOT EXISTS ictsol")
            db.execute("REVOKE ALL ON SCHEMA ictsol FROM PUBLIC")
        initial_schema = """
            CREATE TABLE IF NOT EXISTS tasks (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                title TEXT NOT NULL, minutes INTEGER NOT NULL,
                deadline TEXT, priority TEXT NOT NULL,
                concentration TEXT NOT NULL, place TEXT NOT NULL,
                completed INTEGER NOT NULL DEFAULT 0
            );
            CREATE TABLE IF NOT EXISTS conditions (
                id INTEGER PRIMARY KEY CHECK (id = 1),
                level TEXT NOT NULL, updated_at TEXT NOT NULL
            );
        """
        if postgres:
            initial_schema = initial_schema.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
        db.executescript(initial_schema)
        # 既存の匿名データは所有者を推測せず保持し、ログイン利用者には公開しない。
        if postgres:
            db.execute("ALTER TABLE tasks ADD COLUMN IF NOT EXISTS user_id INTEGER")
        elif "user_id" not in {row[1] for row in db.execute("PRAGMA table_info(tasks)")}:
            db.execute("ALTER TABLE tasks ADD COLUMN user_id INTEGER")
        schema = """
            CREATE TABLE IF NOT EXISTS users (
                id INTEGER PRIMARY KEY, username TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS sessions (
                token_hash TEXT PRIMARY KEY, user_id INTEGER NOT NULL, expires_at REAL NOT NULL
            );
            CREATE TABLE IF NOT EXISTS auth_attempts (
                bucket TEXT PRIMARY KEY, count INTEGER NOT NULL, started_at REAL NOT NULL
            );
            CREATE TABLE IF NOT EXISTS user_conditions (
                user_id INTEGER PRIMARY KEY, level TEXT NOT NULL, updated_at TEXT NOT NULL
            );
            CREATE TABLE IF NOT EXISTS calendar_events (
                user_id INTEGER NOT NULL, event_key TEXT NOT NULL,
                starts_at TEXT NOT NULL, ends_at TEXT NOT NULL,
                PRIMARY KEY (user_id, event_key)
            );
            CREATE TABLE IF NOT EXISTS calendar_sync (
                user_id INTEGER PRIMARY KEY, synced_at TEXT NOT NULL,
                window_start TEXT NOT NULL, window_end TEXT NOT NULL
            );
            CREATE INDEX IF NOT EXISTS tasks_owner ON tasks(user_id);
            CREATE TABLE IF NOT EXISTS activities (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                user_id INTEGER NOT NULL, task_id INTEGER,
                task_title TEXT, condition_level TEXT NOT NULL,
                created_at TEXT NOT NULL
            );
            CREATE INDEX IF NOT EXISTS activities_owner ON activities(user_id, id DESC);
            CREATE TABLE IF NOT EXISTS ai_usage (
                bucket TEXT PRIMARY KEY, count INTEGER NOT NULL, expires_at REAL NOT NULL
            );
        """
        if postgres:
            schema = schema.replace("INTEGER PRIMARY KEY AUTOINCREMENT", "INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY")
            schema = schema.replace("id INTEGER PRIMARY KEY, username", "id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, username")
            schema = schema.replace(" REAL ", " DOUBLE PRECISION ")
        db.executescript(schema)
        if postgres:
            # Supabaseのブラウザ用APIからアプリの内部テーブルを参照させない。
            for role in ("PUBLIC", "anon", "authenticated"):
                if role != "PUBLIC" and not db.execute("SELECT 1 FROM pg_roles WHERE rolname=?", (role,)).fetchone():
                    continue
                db.execute(f"REVOKE ALL ON SCHEMA ictsol FROM {role}")
                db.execute(f"REVOKE ALL ON ALL TABLES IN SCHEMA ictsol FROM {role}")
                db.execute(f"REVOKE ALL ON ALL SEQUENCES IN SCHEMA ictsol FROM {role}")


def tasks(user_id):
    with database() as db:
        return [dict(row) for row in db.execute("SELECT * FROM tasks WHERE user_id=? ORDER BY completed, id DESC", (user_id,))]
